#!/bin/bash
# Generated by fix-postgres-password.js

# Set PostgreSQL environment variables
export PGHOST=localhost
export PGUSER=wab
export PGPASSWORD=SEKRET
export PGDATABASE=wab
export PGPORT=5432

# Run the original command with these environment variables
echo "Starting with database environment variables set..."
cd platform/wab && yarn dev
